service: job-questionmark

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-2
  environment:
    LLM_MODEL_ID: ${env:LLM_MODEL_ID}
    AGENT_ROLE_ARN: ${env:AGENT_ROLE_ARN}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY}
    MAX_INPUT_LENGTH: ${env:MAX_INPUT_LENGTH}
    LOGGING_LEVEL: ${env:LOGGING_LEVEL}

functions:
  api:
    handler: src.main.handler
    timeout: 28
    events:
      - httpApi:
          path: /agent
          method: post
    layers:
      - Ref: PythonRequirementsLambdaLayer

package:
  patterns:
    - '!venv/**'
    - '!tests/**'
    - '!infra/**'
    - 'src/**'
    - 'requirements.txt'
    - '!job_questionmark.egg-info/**'
    - '!.git/**'
    - '!.env'
    - '!.serverless/**'


plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    layer: true             # <--- This tells the plugin to create a Lambda Layer
    slim: true
    dockerizePip: true
    zip: true
    invalidateCaches: true  # optional but helpful during debugging