service: job-questionmark

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-2
  environment:
    LLM_MODEL_ID: ${env:LLM_MODEL_ID}
    AGENT_ROLE_ARN: ${env:AGENT_ROLE_ARN}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY}
    MAX_INPUT_LENGTH: ${env:MAX_INPUT_LENGTH}
    LOGGING_LEVEL: ${env:LOGGING_LEVEL}
    CONTACT_EMAIL: ${env:CONTACT_EMAIL}
    AWS_REGION_DEPLOYMENT: ${env:AWS_REGION_DEPLOYMENT}
    DOMAIN_NAME: ${env:DOMAIN_NAME}
  apiGateway:
    apiKeys:
      - job-questionmark-dev
    usagePlan:
      throttle:
        rateLimit: 5
        burstLimit: 10
      quota:
        limit: 100
        period: WEEK

functions:
  api:
    handler: src.main.handler
    timeout: 28
    events:
      - http:
          path: /agent
          method: post
          private: true
          cors:
            origin: '${env:DOMAIN_NAME},http://localhost:3000'
            headers:
              - Content-Type
              - X-Api-Key
            allowCredentials: false
    layers:
      - Ref: PythonRequirementsLambdaLayer
  
  contact:
    handler: src.main.handler
    timeout: 28
    events:
      - http:
          path: /contact
          method: post
          private: true
          cors:
            origin: '${env:DOMAIN_NAME},http://localhost:3000'
            headers:
              - Content-Type
              - X-Api-Key
            allowCredentials: false
    layers:
      - Ref: PythonRequirementsLambdaLayer

package:
  patterns:
    - '!venv/**'
    - '!tests/**'
    - '!infra/**'
    - 'src/**'
    - 'requirements.txt'
    - '!analyze_deps.py'
    - '!package/**'
    - '!layers/**'
    - '!**/__pycache__/**'
    - '!.env'
    - '!.serverless/**'
    - '!.github/**'
    - '!.pytest_cache/**'
    - '!.coverage'
    - '!htmlcov/**'
    - '!.vscode/**'
    - '!.idea/**'
    - '!*.log'
    - '!setup.py'

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    layer: true
    slim: true
    dockerizePip: true
    zip: true
    invalidateCaches: true