service: job-questionmark

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-2
  environment:
    # Add your environment variables here or use secrets manager/SSM
    LLM_MODEL_ID: ${env:LLM_MODEL_ID}
    AGENT_ROLE_ARN: ${env:AGENT_ROLE_ARN}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY}
    MAX_INPUT_LENGTH: ${env:MAX_INPUT_LENGTH}
    LOGGING_LEVEL: ${env:LOGGING_LEVEL}

functions:
  api:
    handler: src.main.handler
    timeout: 28
    events:
      - httpApi:
          path: /agent
          method: post

package:
  patterns:
    - '!venv/**'
    - '!tests/**'
    - '!infra/**'
    - 'src/**'
    - 'requirements.txt'
    - '.env'

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: true
    zip: true
    slim: true
    layer: false
    pipCmdExtraArgs:
      - '--upgrade'
  offline:
    useChildProcesses: true
    noPrependStageInUrl: true
    httpPort: 3000 