name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Python Requirements Plugin
        run: npm install --save-dev serverless-python-requirements

      - name: Install Serverless Offline Plugin
        run: npm install --save-dev serverless-offline

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Set Serverless Access Key
        run: echo "SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Deploy with Serverless
        run: sls deploy --stage prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          LLM_MODEL_ID: ${{ secrets.LLM_MODEL_ID }}
          APP_API_BASE_URL: ${{ secrets.APP_API_BASE_URL }}
          AGENT_MODEL_ID: ${{ secrets.AGENT_MODEL_ID }}
          AGENT_ROLE_ARN: ${{ secrets.AGENT_ROLE_ARN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MAX_INPUT_LENGTH: ${{ secrets.MAX_INPUT_LENGTH }}
          LOGGING_LEVEL: ${{ secrets.LOGGING_LEVEL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          AWS_REGION_DEPLOYMENT: ${{ secrets.AWS_REGION_DEPLOYMENT }}
          APP_API_KEY_DEV: ${{ secrets.APP_API_KEY_DEV }}
